### ISSUE TITLE
screenrecording.gif is too fast

### ISSUE THREAD

**Issue by aleksejrs** [ijgnd/anki__browser_MaximizeHide_TableEditor#1]

**Comment by ijgnd** [comment]
Thanks for your interest. If it's slower it's bigger. I don't want to embed a 25mb file. I don't know how to solve this. If you have a guide on how to make smaller gifs with the same resolution this would be very welcome.

You could try an mp4 version at: https://streamable.com/bi8w1 I added this link to the description.
