### ISSUE TITLE
Addon page on ankiweb needs edition about getting one line by notes

### ISSUE THREAD

**Issue by Fred-Vatin** [ijgnd/anki__browser_MaximizeHide_TableEditor#3]
Add-on version | Anki | OS 
------------------ | ---- | ---
2020-07-02 | ⁨2.1.37 | Win 10 x64 pro (french)1909

It is stated that

> Otherwise for note types that have multiple cards the view wouldn't change as long as you go through cards of the same note. You need to have [Advanced Browser](https://ankiweb.net/shared/info/874215009).

This add-on has no option as shown in the gif. Instead one need to download another one : [Card browser: List only one card per note](https://ankiweb.net/shared/info/797076357)

**Comment by ijgnd** [comment]
Thank you for notifying me about this. I fixed the ankiweb listing.

The functionality of "Card browser: List only one card per note" used to be built into the "Advanced Browser". I made the description for my add-on before it was a separate add-on and didn't think of updating the description later.
