### ISSUE TITLE
Blank Sidebar with Maximized Browser

### ISSUE THREAD

**Issue by schmidhauser** [ijgnd/anki__browser_MaximizeHide_TableEditor#4]
If I open the Browser without Sidebar, and then use my shortcut to show the Sidebar, the left side remains blank – I first have to close and then re-open the Browser. I wonder if it would somehow be possible to show it directly.

<img width="630" alt="sidebar-missing" src="https://user-images.githubusercontent.com/519178/138810213-2993fec9-3f2d-4d4b-bc08-a6d2be633f32.png">

**Comment by ijgnd** [comment]
Thanks for letting me know. 

This should be a problem for the new sidebar from .41+

For me it's enough to run a search inside the sidebar to show its contents. I added one line that does this which I just copied from the end of the new sidebar setup in browser.py, see [here](https://github.com/ankitects/anki/blob/036d04a7b1514fde0018280a79e98066275dae9c/qt/aqt/browser/browser.py#L529).

change [this line](https://github.com/ijgnd/anki__browser_MaximizeHide_TableEditor/blob/6bee969739d35d221cbe608ede04dc4edfa13d08/src/browser_MaximizeHide_TableEditor.py#L157) in my source code:

        if not self.sidebarDockWidget.isVisible():
            self.sidebarDockWidget.setVisible(True)
            self.mw.progress.timer(10, self.sidebar.refresh, False)
        else:

This should fix it. Let me know if this doesn't work for you.

**Comment by schmidhauser** [comment]
This does indeed fix it. Brilliant. Thank you!
